### PR TITLE
Added BlocklyProp

### PR DESCRIPTION
**Pull request by DarkmatterVale**
Hi,

I have just added some basic information to the README.md file. It now shows some of the projects that will be included in the webpages. I will add more to the README once I get the chance to add some pages for BlocklyProp.

Thanks,
Vale

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
I will improve this PR to include the BlocklyProp page soon, so I will close this for now.

Sorry for any inconvenience.

**Comment by bweir** [comment]
Hey, cool, thanks! Let me know if you need help integrating with the new site. I'm still experimenting with how pages are going to work, but you can see what I have so far here.

http://parallaxinc.github.io/projects/propelleride/

**Comment by DarkmatterVale** [comment]
Thanks! I have taken a look, and I think that the pages look awesome! If you don't mind me asking, what changes are you planning on making?

Yes, I do need a little help. How do I test my changes?

Thanks again!

**Comment by DarkmatterVale** [comment]
Also, do you mind if I borrow some of the phrases that you used on the PropellerIDE project page?

I can show you the final product before anything gets to be viewed publicly if you want.

Thanks,
Vale

**Comment by bweir** [comment]
Thanks! Well, you'll notice right now there's a lot of hand-coded things.
I'd like to instead call the github api so that the pages are generated
dynamically from the project READMEs. Then all of the projects will be
supported for free without everyone having to do what you're gonna do. :p

You will need to set up a recent Jekyll environment (2.5 at least). If you
are on Debian, all you have to do is check out the project and type 'make
install' and it should take care of it on its own.

**Comment by DarkmatterVale** [comment]
Sadly, I am on a Mac environment. Is there anything different I need to do because of this?

**Comment by bweir** [comment]
Haha you mean plagiarize? >.< If you paraphrase and it's relevant to your
project, it's fine, but otherwise I think it would reflect poorly on us to
directly reuse copy. And sure, I'd like to see what you create.

**Comment by bweir** [comment]
Hmmm... well you'll need to install ruby and pygments, then after that,  it
should be the same. Most of the items are installed as ruby gems.

**Comment by DarkmatterVale** [comment]
Ok; I will install these packages and see if this works. Thanks for the help!

I will not plagiarize, but thanks for the reminder. Since I am new to this being a freshman in high school, I sometimes forget....I will  make sure that they are pretty different.

**Comment by bweir** [comment]
Hehehe, it's all good. You're off to a good start. A lot of developers don't discover version control until they're already knee-deep in projects (like myself!). It's a joy to see someone so young using GitHub. =P

**Comment by DarkmatterVale** [comment]
It definitely is a great thing to get familiar with, as it is becoming more and more important nowadays.

I think I have a prototype ready. Can you take a look ( as long as it isn't a bother of course )?

Thanks,
Vale

**Comment by bweir** [comment]
It's looking pretty good. You actually added all the bootstrap tags, yay! :p

Only one thing: it looks like a tab got replaced with spaces in the
makefile, which will probably break it (makefiles are extremely particular
about the syntax they'll accept) so if you could change that back it'd be
great. But if I haven't heard from you, I'll just fix it myself when I'm on
my computer later and merge your changes in.

**Comment by DarkmatterVale** [comment]
Sorry, that was a mistake. Thanks for catching that :) !

Yeah, I added ( hopefully ) all of the tags currently relevant to the project. Once there is a standard release, I will have to update this to include the release, but until then it should be good.

**Comment by bweir** [comment]
Oops! I didn't notice this before but you forgot to change one of the images. It's still referencing one of mine. Anywho, we can get that fixed pretty quickly. http://parallaxinc.github.io/projects/blocklyprop/

**Comment by DarkmatterVale** [comment]
I didn't notice this either...Sorry!

I am fixing right now....give me a couple of minutes please...

**Comment by DarkmatterVale** [comment]
https://github.com/parallaxinc/parallaxinc.github.io/pull/2

**Pull request merged**
