### PR TITLE
Fixed wrong image reference

### PR DESCRIPTION
**Pull request by DarkmatterVale**
-Added a new image
-Changed reference to new image

### CODE REVIEW

**Comment by bweir** [comment]
Cool thanks!

**Comment by DarkmatterVale** [comment]
No problem!

Thanks for all of the help!

**Comment by bweir** [comment]
Hey, no problem!

Now I'm curious... how would I go about getting the LameStation supported in Blockly? What's required? Also, is this the homepage?

http://blocklyprop.creatingfuture.eu/index.html

The first thing I did when I looked at your page was try to figure out how to run Blockly (since it's web-based!) If you look at the "links" field on the page, you can see that you can actually add any kind of link you want like that.

Or a giant button on the homepage would be awesome! I added one. Tell me what you think.

Also, where is this being hosted?

**Comment by DarkmatterVale** [comment]
Well, if you would like to get LameStation supported in Blockly, you will probably have to talk to me since most of the UI work falls/will eventually fall on me :). I am not sure what is required, but I definitely think it is do-able.  What requirements are there for the LameStation specifically ( i.e. it requires a whole different compiler and cannot be programmed using PropellerIDE )?

Yes, that is currently the homepage. We will make some edits once we get some more stuff done. I am writing a lot of blocks, and there is the possibility for Basic Stamp 2 support so once some more of the vision comes into place, the homage will be updated.

Thanks for adding all of that stuff! It looks much nicer now.

Currently, Michel is hosting the server. I have a local one running on my computer so I can test changes I make to the PHP code, but that is it.

**Comment by bweir** [comment]
Hahaha, no, nothing like that. It uses plain old Spin, but it uses Spin for some interesting things, like it has its own Spin-based image/music formats and its own library of functions. I've never worked with an environment like Blockly before so I really don't know how things translate between them.

Ah, cool! Glad I found the right one. =P

Ah, I don't know Michel. Haha. Is Blockly in production? Are classes using it yet?

**Comment by DarkmatterVale** [comment]
After looking at the SDK, I definitely think it is possible to add LameStation support to BlocklyProp. The only hard thing that I might need to get a little help from Michel with is getting the libraries all setup. Other than that, programming it shouldn't be a problem! Can it be programmed using C, or just Spin?

No, sadly it is still an in-progress project. I am working on two very challenging and major additions to the project right now, and Michel is also working on some core additions. I can explain more if you want, but it gets pretty confusing. I think we are about ~2 months ( very beginning of April ) to getting a production-ready v1.0 out. And so no, 0 classes are currently using Blockly.

**Comment by bweir** [comment]
Ah, cool! It's super duper Spin all the way. =P I'd spend the rest of my
life working on this to get C support for the SDK too. I've been working on
this for years and it's still not what I'd call finished!

Haha, no problem. I don't know much about the project so I wasn't sure
where you guys were at. I'd be really excited to see Blockly support for
LameStation as I'm very interested in targeting a younger crowd going
forward.

On Sun, Feb 8, 2015 at 9:42 AM, Vale notifications@github.com wrote:

> After looking at the SDK, I definitely think it is possible to add
> LameStation support to BlocklyProp. The only hard thing that I might need
> to get a little help from Michel with is getting the libraries all setup.
> Other than that, programming it shouldn't be a problem! Can it be
> programmed using C, or just Spin?
> 
> No, sadly it is still an in-progress project. I am working on two very
> challenging and major additions to the project right now, and Michel is
> also working on some core additions. I can explain more, but it gets pretty
> confusing. I think we are about ~2 months to getting a production-ready
> v1.0 out. And so no, 0 classes are currently using Blockly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parallaxinc/parallaxinc.github.io/pull/2#issuecomment-73421716
> .

## 

_Brett Weir_, Founder

Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com

**Comment by DarkmatterVale** [comment]
Yea, I would be really excited to see support for it as well. I am hoping to buy a LamStation soon, and since I am horrendous at programming Spin some Blockly support would be nice :) .

Can you email me regarding this? Can you include some of the specifics about LameStation in the email ( such as the requirements for someone to go from having the standard PropellerIDE installation to being able to program the LameStation )? Is it alright if I bring this up with the "project heads" about support for LameStation?

Also and finally, do you mind if it is a little bit until support for LameStation is released? We need to get a working version of Blockly released before we can spend time working on additions.

**Comment by bweir** [comment]
Hahaha. :P Sure, I'd be happy to email you, but it doesn't look like you have an email address posted on your account publicly. And that's no problem. Who are the project heads anyhow?

And absolutely. I'm happy enough to hear that you'd be interested in supporting it; LameStation is still under quite active development and a formal launch is still months (and months) away.

**Comment by DarkmatterVale** [comment]
Ha! I might be able to help a little on tutorials once ( and still possibly an if sadly ) I get my LameStation if I have enough time. That is of course if you would like any help....

Yeah, sorry. My email address: valetolpegin@gmail.com

The project leads: Jeff Martin, Ken Gracey, Michel Lampo, and Andy Lindsay.

**Pull request merged**
